import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#ffffff',
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 20,
        paddingVertical: 15,
        backgroundColor: '#fff',
        borderBottomWidth: 1,
        borderBottomColor: '#f0f0f0',
    },
    backButton: {
        width: 44,
        height: 44,
        justifyContent: 'center',
        alignItems: 'flex-start',
    },
    locationButton: {
        width: 44,
        height: 44,
        justifyContent: 'center',
        alignItems: 'flex-end',
    },
    title: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#333',
        position: 'absolute',
        left: 0,
        right: 0,
        textAlign: 'center',
        pointerEvents: "none"
    },
    mapContainer: {
        flex: 1,
        overflow: 'visible',
    },
    webView: {
        flex: 1,
    },
    textInput: {
        height: 30,
        fontSize: 16,
        textAlign: 'left',
        color: '#000',
        paddingVertical: 0,
        textAlignVertical: 'center',
        justifyContent: 'center',
    },
    searchContainer: {
        position: 'absolute',
        top: 12,
        left: 20,
        right: 20,
        paddingVertical: 12,
        backgroundColor: '#fff',
        borderRadius: 10,
        paddingHorizontal: 15,
        zIndex: 10,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.15,
        shadowRadius: 4,
        elevation: 5,
    },
    storeInfoContainer: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        backgroundColor: '#fff',
        borderTopLeftRadius: 20,
        borderTopRightRadius: 20,
        padding: 20,
        paddingTop: 30,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: -2 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 5,
        minHeight: 220,
    },
    closeButton: {
        position: 'absolute',
        top: 15,
        right: 15,
        zIndex: 1,
        width: 44,
        height: 44,
        justifyContent: 'center',
        alignItems: 'center',
    },
    storeName: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#333',
        marginBottom: 8,
    },
    storeAddress: {
        fontSize: 14,
        color: '#666',
        marginBottom: 8,
    },
    storePhone: {
        fontSize: 13,
        color: '#4285F4',
        marginBottom: 12,
    },
    loadingOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 100,
    },
    loadingText: {
        marginTop: 12,
        fontSize: 18,
        color: '#fff',
        fontWeight: '500',
    },
    modalHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        padding: 16,
        backgroundColor: '#fff',
        borderBottomWidth: 1,
        borderBottomColor: '#e0e0e0',
    },
    modalTitle: {
        fontSize: 18,
        fontWeight: 'bold',
    },
    modalCloseButton: {
        padding: 4,
    },
    searchTextPlaceholder: {
        fontSize: 16,
        color: '#999',
    },
    searchTextActive: {
        fontSize: 16,
        color: '#000',
    },
    btnContainer:{
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: 20,
    },
    statusBar: {
        backgroundColor: "#fff"
    },
    dragHandle: {
        height: 30,
        justifyContent: 'center',
        alignItems: 'center',
        width: '100%',
    },
    dragHandleBar: {
        width: 40,
        height: 4,
        backgroundColor: '#ccc',
        borderRadius: 2,
    },
    storeInfoWhiteOverlay: {
        backgroundColor: '#fff',
    },
    modalContent: {
        flex: 1,
        paddingTop: 0,
    },
    modalEmptyView: {
        width: 28,
    },
    postcodeStyle: {
        flex: 1,
    },
    storePanelContainer: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
    },
});
