import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#ffffff",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: 20,
    backgroundColor: "#fff",
  },
  backButton: {
    width: 44,
    height: 44,
    justifyContent: "center",
    alignItems: "flex-start",
  },
  title: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#333",
    position: "absolute",
    left: 0,
    right: 0,
    textAlign: "center",
  },
  placeholder: {
    width: 40,
  },
  content: {
    flex: 1,
    backgroundColor: "#fff",
    justifyContent: "center",
    paddingVertical: 10,
    marginVertical: 5,
    borderRadius: 10,
    boxShadow: "0 0px 6px rgba(0,0,0,0.1)",
  },
  tabContainer: {
    flexDirection: "row",
    justifyContent: "space-evenly",
    alignItems: "center",
    height: 50,
  },
  tabButton: {
    justifyContent: "center",
    alignItems: "center",
    flex: 1,
    height: 50,
    borderBottomWidth: 1,
    borderBottomColor: "#E0E0E0",
  },
  tabButtonActive: {
    justifyContent: "center",
    alignItems: "center",
    flex: 1,
    height: 50,
    borderBottomWidth: 2,
    borderBottomColor: "#ef7810",
  },
  tabButtonText: {
    color: "#999",
    fontSize: 15,
  },
  tabButtonTextActive: {
    color: "#000",
    fontSize: 15,
    fontWeight: "600",
  },
  listTouchable: {
    justifyContent: "flex-start",
  },
  listContainer: {
    flexDirection: "row",
    borderRadius: 10,
    overflow: "hidden",
    justifyContent: "flex-start",
    alignItems: "center",
    paddingVertical: 20,
    paddingHorizontal: 10,
  },
  listImageContainer: {
    width: 130,
    height: 130,
  },
  listImage: {
    width: "100%",
    height: "100%",
  },
  listInfoContainer: {
    flex: 1,
    paddingHorizontal: 15,
    justifyContent: "center",
  },
  listcategoryName: {
    fontSize: 12,
    color: "#888",
  },
  listproductName: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#000",
    marginBottom: 4,
  },
  listprice: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#ef7810",
  },
  listButtonContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-around",
    marginVertical: 10,
    marginHorizontal: 20,
  },
  negoCancelButton: {
    flex: 1,
    backgroundColor: "#fff",
    borderColor: "#ef7810",
    borderWidth: 1,
    paddingVertical: 6,
    borderRadius: 6,
    marginRight: 8,
    justifyContent: "center",
    alignItems: "center",
  },
  negoCancelButtonText: {
    color: "#ef7810",
    fontSize: 14,
    fontWeight: "bold",
  },
  historyTouchable: {
    justifyContent: "flex-start",
  },
  historyContainer: {
    flexDirection: "row",
    borderRadius: 10,
    overflow: "hidden",
    justifyContent: "flex-start",
    alignItems: "center",
    paddingVertical: 20,
    paddingHorizontal: 10,
  },
  historyImageContainer: {
    width: 130,
    height: 130,
  },
  historyImage: {
    width: "100%",
    height: "100%",
  },
  historyInfoContainer: {
    flex: 1,
    paddingHorizontal: 15,
    justifyContent: "center",
  },
  historycategoryName: {
    fontSize: 12,
    color: "#888",
  },
  historyproductName: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#000",
    marginBottom: 4,
  },
  historyofferedPrice: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#ef7810",
  },
  historyButtonContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-around",
    marginVertical: 10,
    marginHorizontal: 20,
  },
  approveButton: {
    flex: 1,
    backgroundColor: "#fff",
    borderColor: "#ef7810",
    borderWidth: 1,
    paddingVertical: 6,
    borderRadius: 6,
    marginRight: 8,
    justifyContent: "center",
    alignItems: "center",
  },
  approveButtonText: {
    color: "#ef7810",
    fontSize: 14,
    fontWeight: "bold",
  },
  rejectButton: {
    flex: 1,
    backgroundColor: "#fff",
    borderColor: "#ef7810",
    borderWidth: 1,
    paddingVertical: 6,
    borderRadius: 6,
    marginLeft: 8,
    justifyContent: "center",
    alignItems: "center",
  },
  rejectButtonText: {
    color: "#ef7810",
    fontSize: 14,
    fontWeight: "bold",
  },
  moreButton: {
    backgroundColor: "#fff",
    borderColor: "#ddd",
    borderWidth: 1,
    paddingVertical: 6,
    paddingHorizontal: 8,
    borderRadius: 6,
    marginLeft: 8,
    justifyContent: "center",
    alignItems: "center",
  },
});
