import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#ffffff",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: 20,
    backgroundColor: "#fff",
  },
  backButton: {
    width: 44,
    height: 44,
    justifyContent: "center",
    alignItems: "flex-start",
  },
  title: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#333",
    position: "absolute",
    left: 0,
    right: 0,
    textAlign: "center",
  },
  placeholder: {
    width: 40,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#333",
  },
  addProductButton: {
    borderWidth: 1,
    borderColor: "#ef7810",
    marginHorizontal: 20,
    marginBottom: 10,
    paddingVertical: 10,
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
  },
  content: {
    flex: 1,
    backgroundColor: "#fff",
    justifyContent: "center",
    paddingVertical: 10,
    marginVertical: 5,
    borderRadius: 10,
    boxShadow: "0 0px 6px rgba(0,0,0,0.1)",
  },
  productTouchable: {
    justifyContent: "flex-start",
  },
  productContainer: {
    flexDirection: "row",
    borderRadius: 10,
    overflow: "hidden",
    justifyContent: "flex-start",
    alignItems: "center",
    paddingVertical: 20,
    paddingHorizontal: 10,
  },
  productImageContainer: {
    width: 130,
    height: 130,
  },
  productImage: {
    width: "100%",
    height: "100%",
  },
  productInfoContainer: {
    flex: 1,
    paddingHorizontal: 15,
    justifyContent: "center",
  },
  categoryName: {
    fontSize: 12,
    color: "#888",
  },
  productName: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#000",
    marginBottom: 4,
  },
  price: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#ef7810",
  },
  productButtonContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-around",
    marginVertical: 10,
    marginHorizontal: 20,
  },
  saleButton: {
    flex: 1,
    backgroundColor: "#fff",
    borderColor: "#ef7810",
    borderWidth: 1,
    paddingVertical: 6,
    borderRadius: 6,
    marginRight: 8,
    justifyContent: "center",
    alignItems: "center",
  },
  saleButtonText: {
    color: "#ef7810",
    fontSize: 14,
    fontWeight: "bold",
  },
  negoButton: {
    flex: 1,
    backgroundColor: "#fff",
    borderColor: "#ef7810",
    borderWidth: 1,
    paddingVertical: 6,
    borderRadius: 6,
    marginLeft: 8,
    justifyContent: "center",
    alignItems: "center",
  },
  negoButtonText: {
    color: "#ef7810",
    fontSize: 14,
    fontWeight: "bold",
  },
  moreButton: {
    backgroundColor: "#fff",
    borderColor: "#ddd",
    borderWidth: 1,
    paddingVertical: 6,
    paddingHorizontal: 8,
    borderRadius: 6,
    marginLeft: 8,
    justifyContent: "center",
    alignItems: "center",
  },
});
