import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#ffffff",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: 20,
    backgroundColor: "#fff",
  },
  backButton: {
    width: 44,
    height: 44,
    justifyContent: "center",
    alignItems: "flex-start",
  },
  title: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#1F2937",
    position: "absolute",
    left: 0,
    right: 0,
    textAlign: "center",
    pointerEvents: "none"
  },
  placeholder: {
    width: 40,
  },
  tabContainer: {
    flexDirection: "row",
    justifyContent: "space-evenly",
    alignItems: "center",
    height: 50,
  },
  tabButton: {
    justifyContent: "center",
    alignItems: "center",
    flex: 1,
    height: 50,
    borderBottomWidth: 1,
    borderBottomColor: "#E5E7EB",
  },
  tabButtonActive: {
    justifyContent: "center",
    alignItems: "center",
    flex: 1,
    height: 50,
    borderBottomWidth: 2,
    borderBottomColor: "#ef7810",
  },
  tabButtonText: {
    color: "#9CA3AF",
    fontSize: 15,
  },
  tabButtonTextActive: {
    color: "#1F2937",
    fontSize: 15,
    fontWeight: "600",
  },
  negoProduct: {
    backgroundColor: "#fff",
    marginTop: 16,
    marginBottom: 12,
    marginHorizontal: 16,
    borderRadius: 12,
    boxShadow: "0 2px 8px rgba(0, 0, 0, 0.08)",
    overflow: "hidden",
  },
  productContainer: {
    flexDirection: "row",
    paddingVertical: 16,
    paddingHorizontal: 16,
    gap: 16,
    alignItems: "center",
  },
  productImageContainer: {
    width: 150,
    height: 150,
    borderRadius: 12,
    overflow: "hidden",
    backgroundColor: "#f5f5f5",
  },
  productImage: {
    width: "100%",
    height: "100%",
    resizeMode: "cover",
  },
  productInfoContainer: {
    flex: 1,
    justifyContent: "center",
    gap: 6,
  },
  categoryText: {
    fontSize: 11,
    color: "#6B7280",
    fontWeight: "600",
    backgroundColor: "#F3F4F6",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 6,
    alignSelf: "flex-start",
  },
  productNameText: {
    fontSize: 15,
    fontWeight: "600",
    color: "#1F2937",
    lineHeight: 20,
  },
  registPriceText: {
    fontSize: 12,
    color: "#9CA3AF",
    textDecorationLine: "line-through",
  },
  negoRequestProduct: {
    backgroundColor: "#fff",
    marginTop: 16,
    marginBottom: 12,
    marginHorizontal: 16,
    borderRadius: 12,
    boxShadow: "0 2px 8px rgba(0, 0, 0, 0.08)",
    overflow: "hidden",
  },
  negoRequestProductContainer: {
    flexDirection: "row",
    paddingVertical: 16,
    paddingHorizontal: 16,
    gap: 16,
    alignItems: "center",
  },
  negoRequestProductImageContainer: {
    width: 150,
    height: 150,
    borderRadius: 12,
    overflow: "hidden",
    backgroundColor: "#f5f5f5",
  },
  negoRequestProductImage: {
    width: "100%",
    height: "100%",
    resizeMode: "cover",
  },
  negoRequestproductInfoContainer: {
    flex: 1,
    justifyContent: "center",
    gap: 6,
  },
  negoStatusAndPriceContainer: {
    gap: 5,
  },
  negoStatusText: {
    fontSize: 12,
    color: "#6B7280",
    fontWeight: "500",
  },
  negoPriceText: {
    fontSize: 17,
    fontWeight: "700",
    color: "#EF7810",
    marginTop: 2,
  },
  requestor: {
    flexDirection: "row",
    gap: 10,
    fontSize: 12,
    color: "#6B7280",
  },
  detailButtonContainer: {
    borderTopWidth: 1,
    borderTopColor: "#F5F5F5",
    paddingVertical: 12,
    paddingHorizontal: 16,
  },
  detailButton: {
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderRadius: 8,
    paddingVertical: 10,
    borderColor: "#ef7810",
  },
  detailButtonText: {
    fontWeight: "600",
    color: "#ef7810",
    fontSize: 13,
  },
  buttonsContainer: {
    borderTopWidth: 1,
    borderTopColor: "#F5F5F5",
    paddingTop: 12,
    paddingBottom: 16,
  },
  requestButtonContainer: {
    flexDirection: "row",
    paddingHorizontal: 16,
    gap: 8,
  },
  approveButtonContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderRadius: 8,
    paddingVertical: 10,
    borderColor: "#ef7810",
  },
  approveButtonText: {
    fontWeight: "600",
    color: "#ef7810",
    fontSize: 13,
  },
  rejectButtonContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#F9FAFB",
    borderWidth: 1,
    borderRadius: 8,
    paddingVertical: 10,
    borderColor: "#D1D5DB",
  },
  rejectButtonText: {
    fontWeight: "600",
    color: "#4B5563",
    fontSize: 13,
  },
  moreButton: {
    backgroundColor: "#fff",
    borderColor: "#ddd",
    borderWidth: 1,
    paddingHorizontal: 4,
    height: 30,
    borderRadius: 6,
    marginLeft: 8,
    justifyContent: "center",
    alignItems: "center",
  },



  
  // 모달 스타일
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContent: {
    backgroundColor: "#fff",
    borderRadius: 12,
    minWidth: 160,
    overflow: "hidden",
    elevation: 5,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  modalButton: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 16,
    paddingHorizontal: 20,
    gap: 12,
  },
  modalButtonText: {
    fontSize: 16,
    color: "#333",
    fontWeight: "500",
  },
  modalDivider: {
    height: 1,
    backgroundColor: "#F0F0F0",
  },

  deleteModalContent: {
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: 24,
    width: "85%",
    maxWidth: 340,
    elevation: 5,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  deleteModalTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#1F2937",
    marginBottom: 12,
    textAlign: "center",
  },
  deleteModalMessage: {
    fontSize: 14,
    color: "#6B7280",
    lineHeight: 22,
    textAlign: "center",
    marginBottom: 24,
  },
  deleteModalButtons: {
    flexDirection: "row",
    gap: 12,
  },
  deleteModalButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 8,
    alignItems: "center",
  },
  cancelButton: {
    backgroundColor: "#F3F4F6",
  },
  modalCancelButtonText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#4B5563",
  },
  confirmButton: {
    backgroundColor: "#FF3B30",
  },
  confirmButtonText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#fff",
  },
});
