import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#f8f8f8",
    },
    header: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        padding: 20,
        backgroundColor: "#fff",
    },
    backButton: {
        width: 44,
        height: 44,
        justifyContent: "center",
        alignItems: "flex-start",
    },
    title: {
        fontSize: 18,
        fontWeight: "bold",
        color: "#333",
        position: "absolute",
        left: 0,
        right: 0,
        textAlign: "center",
        pointerEvents: "none",
    },
    placeholder: {
        width: 40,
    },
    content: {
        flex: 1,
        padding: 16,
    },
    wrapper:{
        paddingHorizontal: 12,
        paddingVertical: 8,
        backgroundColor: "#fff",
    },
    section: {
        marginBottom: 20,
    },
    label: {
        fontSize: 16,
        fontWeight: "600",
        color: "#EF7810",
        marginBottom: 8,
    },
    typeContainer: {
        flexDirection: "row",
        justifyContent: "space-between",
    },
    typeButton: {
        flex: 1,
        paddingVertical: 10,
        paddingHorizontal: 12,
        borderRadius: 4,
        borderWidth: 1,
        borderColor: "#ddd",
        backgroundColor: "#fff",
        alignItems: "center",
        marginHorizontal: 4,
    },
    typeButtonActive: {
        borderColor: "#EF7810",
        backgroundColor: "#FFF5F0",
    },
    typeButtonText: {
        fontSize: 13,
        fontWeight: "500",
        color: "#999",
    },
    typeButtonTextActive: {
        color: "#EF7810",
        fontWeight: "600",
    },
    input: {
        borderWidth: 1,
        borderColor: "#ddd",
        borderRadius: 4,
        paddingHorizontal: 12,
        paddingVertical: 10,
        fontSize: 16,
        color: "#000",
        fontFamily: "System",
    },
    row: {
        flexDirection: "row",
        justifyContent: "space-between",
    },
    flex: {
        flex: 1,
        marginHorizontal: 4,
    },
    checkboxRow: {
        flexDirection: "row",
        alignItems: "center",
        paddingVertical: 8,
    },
    checkbox: {
        width: 20,
        height: 20,
        borderRadius: 2,
        borderWidth: 1,
        borderColor: "#ddd",
        justifyContent: "center",
        alignItems: "center",
        marginRight: 8,
        backgroundColor: "#fff",
    },
    checkboxActive: {
        borderColor: "#EF7810",
        backgroundColor: "#EF7810",
    },
    checkboxLabel: {
        fontSize: 16,
        color: "#000",
    },
    bottomButtonContainer: {
        flexDirection: "row",
        gap: 8,
        padding: 16,
        backgroundColor: "#fff",
        borderTopWidth: 1,
        borderTopColor: "#eee",
    },
    cancelButton: {
        flex: 1,
        borderWidth: 1,
        borderColor: "#ddd",
        borderRadius: 4,
        paddingVertical: 12,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: "#fff",
    },
    cancelButtonText: {
        fontSize: 14,
        fontWeight: "600",
        color: "#333",
    },
    registerButton: {
        flex: 1,
        borderRadius: 4,
        paddingVertical: 12,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: "#EF7810",
    },
    registerButtonText: {
        fontSize: 14,
        fontWeight: "600",
        color: "#fff",
    },
});
