import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#ffffffff',
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        padding: 20,
        backgroundColor: '#fff',
    },
    backButton: {
        width: 44,
        height: 44,
        justifyContent: 'center',
        alignItems: 'flex-start',
    },
    title: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#333',
        position: 'absolute',
        left: 0,
        right: 0,
        textAlign: 'center',
        pointerEvents: "none",
    },
    placeholder: {
        width: 40,
    },
    cartTopContainer: {
        backgroundColor: '#fff',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 16,
        paddingBottom: 15,
        borderBottomWidth: 1,
        borderBottomColor: '#F0F0F0',
    },
    cartTopLeftSection: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        paddingVertical: 4,
        paddingHorizontal: 4,
    },
    cartTopCheckText: {
        fontSize: 14,
    },
    cartTopSelectAllText: {
        fontSize: 18,
        fontWeight: '600',
        color: '#333',
    },
    cartTopDeleteContainer: {
        flexDirection: 'row',
        justifyContent: 'flex-end',
        gap: 10,
    },
    cartTopDeleteButton: {
        paddingVertical: 2,
        paddingHorizontal: 8,
    },
    cartTopDeleteButtonText: {
        fontSize: 18,
        fontWeight: '400',
        color: '#666',
    },
    cartTopDivider: {
        color: '#D0D0D0',
        fontSize: 14,
        marginHorizontal: 4,
    },
    cartItemContainer: {
        backgroundColor: '#fff',
        borderBottomWidth: 8,
        borderBottomColor: '#F5F5F5',
        paddingVertical: 12,
    },
    cartStoreInfoContainer: {
        paddingVertical: 12,
        paddingHorizontal: 16,
        borderBottomWidth: 1,
        borderBottomColor: '#F0F0F0',
        marginBottom: 8,
    },
    storeCheckboxArea: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        alignSelf: 'flex-start',
    },
    cartStoreNameText: {
        fontSize: 18,
        fontWeight: '700',
        color: '#333',
    },
    productItemWrapper: {
        flexDirection: 'row',
        paddingHorizontal: 16,
        paddingVertical: 12,
        alignItems: 'flex-start',
        borderBottomWidth: 1,
        borderBottomColor: '#F8F8F8',
    },
    productContentArea: {
        flex: 1,
        flexDirection: 'row',
        gap: 12,
    },
    productCheckboxArea: {
        paddingTop: 4,
        paddingRight: 4,
    },
    cartItemDetailContainer: {
        flexDirection: 'row',
        padding: 8,
        gap: 12,
        alignItems: 'center',
    },
    cartItemImgContainer: {
        width: 100,
        height: 100,
        borderRadius: 8,
        justifyContent: 'center',
        borderWidth: 1,
        borderColor: '#E0E0E0',
        alignItems: 'center',
        backgroundColor: '#F9F9F9',
        overflow: 'hidden',
    },
    productImage: {
        width: '100%',
        height: '100%',
        resizeMode: 'cover',
    },
    cartItemInfoContainer: {
        flex: 1,
        gap: 6,
    },
    cartItemNmText: {
        fontSize: 18,
        fontWeight: '600',
        color: '#333',
    },
    cartItemPriceContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
    },
    cartItemSalePriceText: {
        fontSize: 18,
        fontWeight: '600',
        color: '#EF7810',
    },
    cartItemOriginalPriceText: {
        fontSize: 18,
        color: '#999',
        textDecorationLine: 'line-through',
    },
    cartItemQtyContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        paddingVertical: 6,
        paddingHorizontal: 10,
        borderWidth: 1,
        borderColor: '#E0E0E0',
        borderRadius: 6,
        width: 110,
        justifyContent: 'space-between',
        backgroundColor: '#fff',
    },
    cartItemQtyButton: {
        width: 24,
        height: 24,
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 4,
        backgroundColor: '#F5F5F5',
    },
    qtyButtonDisabled: {
        backgroundColor: '#F9F9F9',
        opacity: 0.5,
    },
    qtyText: {
        fontSize: 16,
        fontWeight: '600',
        color: '#333',
        minWidth: 30,
        textAlign: 'center',
    },
    stockText: {
        fontSize: 12,
        color: '#999',
        marginTop: 2,
    },
    cartItemEachPriceContainer: {
        paddingVertical: 8,
        paddingHorizontal: 12,
        flexDirection: 'row',
        justifyContent: 'flex-end',
        alignItems: 'center',
        gap: 8,
    },
    cartItemEachText:{
      fontSize: 14,
      fontWeight: '600',
      color: '#999',
    },
    cartItemEachPriceText: {
        fontSize: 14,
        fontWeight: '600',
        color: '#EF7810',
    },
    cartItemDeleteButton: {
        padding: 8,
        marginLeft: 8,
    },
    cartItemDetailTotalContainer: {
        flexDirection: 'row',
        justifyContent: 'flex-end',
        alignItems: 'center',
        paddingRight: 16,
        paddingTop: 12,
        paddingBottom: 4,
        gap: 8,
    },
    cartItemTotalText: {
        fontSize: 18,
        color: '#999',
    },
    cartItemTotalSalePriceText: {
        fontSize: 18,
        fontWeight: '600',
        color: '#EF7810',
    },
    purchaseContainer: {
        flexDirection: 'column',
        gap: 6,
        paddingVertical: 10,
        paddingHorizontal: 16,
        backgroundColor: '#fff',
        borderTopWidth: 1,
        borderTopColor: '#E0E0E0',
    },
    purchaseSummaryRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 4,
    },
    purchaseText: {
        fontSize: 18,
        color: '#666',
    },
    purchaseValue: {
        fontSize: 18,
        fontWeight: '600',
        color: '#000',
    },
    purchaseValueOriginal: {
        fontSize: 18,
        fontWeight: '700',
        color: '#EF7810',
    },
    purchaseButtonContainer: {
        backgroundColor: '#fff',
        paddingVertical: 18,
        alignItems: 'center',
        borderRadius: 8,
        marginHorizontal: 16,
        marginVertical: 12,
        borderWidth: 2,
        borderColor: '#EF7810',
    },
    purchaseButtonDisabled: {
        backgroundColor: '#ccc',
        borderWidth: 0,
    },
    purchaseButtonWrapper: {
        backgroundColor: '#fff',
    },
    purchaseButtonText: {
        color: '#EF7810',
        fontSize: 18,
        fontWeight: '700',
    },
    purchaseButtonTextDisabled: {
        color: '#fff',
    },
    flatListContent: {
        flexGrow: 1,
    },
    emptyContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingVertical: 100,
    },
    emptyText: {
        fontSize: 16,
        color: '#999',
        marginTop: 16,
    },
});