import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#ffffffff',
    },
    headerContainer: {
        height: 56,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        position: 'relative',
    },
    backButton: {
        position: 'absolute',
        left: 16,
        padding: 8,
    },
    headerTitleText: {
        fontSize: 18,
        fontWeight: '600',
    },
    cartTopContainer: {
        backgroundColor: '#fff',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 6,
        paddingHorizontal: 16,
        borderBottomWidth: 1,
        borderBottomColor: '#f0f0f0',
    },
    cartTopLeftSection: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    cartTopCheckText: {
        fontSize: 14,
    },
    cartTopSelectAllText: {
        fontSize: 12,
        fontWeight: '600',
        color: '#333',
    },
    cartTopDeleteContainer: {
        flexDirection: 'row',
        justifyContent: 'flex-end',
        gap: 10,
    },
    cartTopDeleteButton: {
        paddingVertical: 2,
        paddingHorizontal: 8,
    },
    cartTopDeleteButtonText: {
        fontSize: 12,
        fontWeight: '400',
        color: '#666',
    },
    cartTopDivider: {
        color: '#d0d0d0',
        fontSize: 14,
        marginHorizontal: 4,
    },
    cartItemContainer: {
        backgroundColor: '#fff',
        borderBottomWidth: 1,
        marginVertical: 8,
        marginHorizontal: 12,
        borderBottomColor: '#f0f0f0',
    },
    cartStoreInfoContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 8,
        paddingHorizontal: 12,
        gap: 8,
    },
    cartStoreNameText: {
        fontSize: 14,
        fontWeight: '600',
        color: '#333',
    },
    cartItemDetailContainer: {
        flexDirection: 'row',
        padding: 8,
        gap: 12,
        alignItems: 'center',
    },
    cartItemImgContainer: {
        width: 80,
        height: 80,
        borderRadius: 6,
        justifyContent: 'center',
        borderWidth: 1,
        borderColor: '#cfcfcfff',
        alignItems: 'center',
    },
    cartItemInfoContainer: {
        flex: 1,
        gap: 6,
    },
    cartItemNmContainer: {
        fontSize: 14,
        fontWeight: '600',
        color: '#333',
    },
    cartItemPriceContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
    },
    cartItemSalePriceText: {
        fontSize: 14,
        fontWeight: '600',
        color: '#EF7810',
    },
    cartItemOriginalPriceText: {
        fontSize: 12,
        color: '#999',
        textDecorationLine: 'line-through',
    },
    cartItemQtyContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
        paddingVertical: 4,
        paddingHorizontal: 8,
        borderWidth: 1,
        borderColor: '#e0e0e0',
        borderRadius: 4,
        width: 70,
        justifyContent: 'center',
    },
    cartItemQtyText: {
        fontSize: 12,
        color: '#666',
    },
    cartItemQtyButton: {
        width: 20,
        height: 20,
        justifyContent: 'center',
        alignItems: 'center',
        color: '#666',
    },
    cartItemEachPriceContainer: {
        paddingVertical: 8,
        paddingHorizontal: 12,
        flexDirection: 'row',
        justifyContent: 'flex-end',
        alignItems: 'center',
        gap: 8,
    },
    cartItemEachPriceText: {
        fontSize: 14,
        fontWeight: '600',
        color: '#EF7810',
    },
    cartItemDeleteButton: {
        padding: 8,
    },
    cartItemDeleteButtonText: {
        fontSize: 18,
        color: '#999',
    },
    cartItemDetailTotalContainer: {
        flexDirection: 'row',
        justifyContent: 'flex-end',
        alignItems: 'center',
        paddingRight: 12,
        paddingBottom: 12,
        gap: 8,
        paddingTop: 12,
    },
    cartItemTotalLabel: {
        fontSize: 12,
        color: '#999',
    },
    cartItemTotalOriginalPriceText: {
        fontSize: 12,
        color: '#999',
        textDecorationLine: 'line-through',
    },
    cartItemTotalSalePriceText: {
        fontSize: 14,
        fontWeight: '600',
        color: '#EF7810',
    },
    purchaseContainer: {
        flexDirection: 'column',
        gap: 6,
        paddingVertical: 10,
        paddingHorizontal: 16,
        backgroundColor: '#fff',
        borderTopWidth: 1,
        borderTopColor: '#e0e0e0',
    },
    purchaseSummaryRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    purchaseLabel: {
        fontSize: 14,
        color: '#666',
    },
    purchaseValue: {
        fontSize: 16,
        fontWeight: '600',
        color: '#000',
    },
    purchaseValueOrange: {
        fontSize: 18,
        fontWeight: '700',
        color: '#EF7810',
    },
    purchaseButtonContainer: {
        borderWidth: 1,
        borderColor: '#EF7810',
        paddingVertical: 10,
        alignItems: 'center',
        borderRadius: 6,
    },
    purchaseButtonText: {
        color: '#EF7810',
        fontSize: 16,
        fontWeight: '600',
    },
});