import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#ffffffff',
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        padding: 20,
        backgroundColor: '#fff',
    },
    backButton: {
        width: 44,
        height: 44,
        justifyContent: 'center',
        alignItems: 'flex-start',
    },
    title: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#333',
        position: 'absolute',
        left: 0,
        right: 0,
        textAlign: 'center',
        pointerEvents: "none",
    },
    placeholder: {
        width: 40,
    },
    cartTopContainer: {
        backgroundColor: '#fff',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 16,
        paddingBottom: 15,
        borderBottomWidth: 1,
        borderBottomColor: '#F0F0F0',
    },
    cartTopLeftSection: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    cartTopCheckText: {
        fontSize: 14,
    },
    cartTopSelectAllText: {
        fontSize: 18,
        fontWeight: '600',
        color: '#333',
    },
    cartTopDeleteContainer: {
        flexDirection: 'row',
        justifyContent: 'flex-end',
        gap: 10,
    },
    cartTopDeleteButton: {
        paddingVertical: 2,
        paddingHorizontal: 8,
    },
    cartTopDeleteButtonText: {
        fontSize: 18,
        fontWeight: '400',
        color: '#666',
    },
    cartTopDivider: {
        color: '#D0D0D0',
        fontSize: 14,
        marginHorizontal: 4,
    },
    cartItemContainer: {
        backgroundColor: '#fff',
        borderBottomWidth: 1,
        marginVertical: 8,
        marginHorizontal: 12,
        borderBottomColor: '#F0F0F0',
    },
    cartStoreInfoContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 8,
        paddingHorizontal: 12,
        gap: 8,
    },
    cartStoreNameText: {
        fontSize: 20,
        fontWeight: '600',
        color: '#333',
    },
    cartItemDetailContainer: {
        flexDirection: 'row',
        padding: 8,
        gap: 12,
        alignItems: 'center',
    },
    cartItemImgContainer: {
        width: 80,
        height: 80,
        borderRadius: 6,
        justifyContent: 'center',
        borderWidth: 1,
        borderColor: '#cfcfcfff',
        alignItems: 'center',
    },
    cartItemInfoContainer: {
        flex: 1,
        gap: 6,
    },
    cartItemNmText: {
        fontSize: 18,
        fontWeight: '600',
        color: '#333',
    },
    cartItemPriceContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
    },
    cartItemSalePriceText: {
        fontSize: 18,
        fontWeight: '600',
        color: '#EF7810',
    },
    cartItemOriginalPriceText: {
        fontSize: 18,
        color: '#999',
        textDecorationLine: 'line-through',
    },
    cartItemQtyContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
        paddingVertical: 4,
        paddingHorizontal: 8,
        borderWidth: 1,
        borderColor: '#E0E0E0',
        borderRadius: 4,
        width: 70,
        justifyContent: 'center',
    },
    cartItemQtyText: {
        fontSize: 18,
        color: '#666',
    },
    cartItemQtyButton: {
        width: 20,
        height: 20,
        justifyContent: 'center',
        alignItems: 'center',
        color: '#666',
    },
    cartItemEachPriceContainer: {
        paddingVertical: 8,
        paddingHorizontal: 12,
        flexDirection: 'row',
        justifyContent: 'flex-end',
        alignItems: 'center',
        gap: 8,
    },
    cartItemEachText:{
      fontSize: 14,
      fontWeight: '600',
      color: '#999',
    },
    cartItemEachPriceText: {
        fontSize: 14,
        fontWeight: '600',
        color: '#EF7810',
    },
    cartItemDeleteButton: {
        padding: 8,
    },
    cartItemDeleteButtonText: {
        fontSize: 20,
        color: '#999',
    },
    cartItemDetailTotalContainer: {
        flexDirection: 'row',
        justifyContent: 'flex-end',
        alignItems: 'center',
        paddingRight: 12,
        paddingBottom: 12,
        gap: 8,
        paddingTop: 12,
    },
    cartItemTotalText: {
        fontSize: 18,
        color: '#999',
    },
    cartItemTotalSalePriceText: {
        fontSize: 18,
        fontWeight: '600',
        color: '#EF7810',
    },
    purchaseContainer: {
        flexDirection: 'column',
        gap: 6,
        paddingVertical: 10,
        paddingHorizontal: 16,
        backgroundColor: '#fff',
        borderTopWidth: 1,
        borderTopColor: '#E0E0E0',
    },
    purchaseSummaryRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 4,
    },
    purchaseText: {
        fontSize: 18,
        color: '#666',
    },
    purchaseValue: {
        fontSize: 18,
        fontWeight: '600',
        color: '#000',
    },
    purchaseValueOriginal: {
        fontSize: 18,
        fontWeight: '700',
        color: '#EF7810',
    },
    purchaseButtonContainer: {
        borderWidth: 1,
        borderColor: '#EF7810',
        paddingVertical: 21,
        alignItems: 'center',
        borderRadius: 6,
    },
    purchaseButtonText: {
        color: '#EF7810',
        fontSize: 20,
        fontWeight: '600',
    },
});