import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#fff",
    },
    header: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        padding: 20,
        backgroundColor: "#fff",
    },
    backButton: {
        width: 44,
        height: 44,
        justifyContent: "center",
        alignItems: "flex-start",
    },
    title: {
        fontSize: 18,
        fontWeight: "bold",
        color: "#333",
        position: "absolute",
        left: 0,
        right: 0,
        textAlign: "center",
        pointerEvents: "none",
    },
    placeholder: {
        width: 40,
    },
    content: {
        flex: 1,
        padding: 20,
    },
    section: {
        backgroundColor: '#fff',
        borderRadius: 12,
        padding: 16,
        marginBottom: 16,
        boxShadow: '0 0 4px rgba(0,0,0,0.2)',
    },
    sectionHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        marginBottom: 16,
        paddingBottom: 12,
        borderBottomWidth: 1,
        borderBottomColor: '#f0f0f0',
    },
    sectionTitle: {
        fontSize: 16,
        fontWeight: '700',
        color: '#1a1a1a',
    },
    formGroup: {
        marginBottom: 16,
    },
    label: {
        fontSize: 14,
        fontWeight: '600',
        color: '#333',
        marginBottom: 8,
    },
    helpText: {
        fontSize: 12,
        color: '#999',
        marginTop: 6,
    },
    input: {
        backgroundColor: '#fff',
        borderRadius: 8,
        padding: 12,
        fontSize: 14,
        borderWidth: 1,
        borderColor: '#E0E0E0',
        color: '#1a1a1a',
    },
    inputDisabled: {
        backgroundColor: '#f5f5f5',
        color: '#999',
    },
    passwordChangeButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
        backgroundColor: '#fff',
        borderRadius: 8,
        padding: 14,
        borderWidth: 1,
        borderColor: '#EF7810',
        marginBottom: 16,
    },
    passwordChangeButtonText: {
        fontSize: 14,
        color: '#EF7810',
        fontWeight: '600',
    },
    submitButton: {
        flex: 1,
        backgroundColor: '#EF7810',
        borderRadius: 8,
        paddingVertical: 16,
        alignItems: 'center',
    },
    submitButtonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '600',
    },
    withdrawButton: {
        borderColor: 'red',
        borderWidth: 1,
        borderRadius: 8,
        padding: 16,
        alignItems: 'center',
        marginTop: 8,
        marginBottom: 15,
    },
    buttonContainer:{
        flexDirection: 'row',
        gap: 12,
    },
    backBtn:{
        flex: 1,
        borderWidth: 1,
        borderColor: '#d0d0d0',
        borderRadius: 8,
        paddingVertical: 16,
        alignItems: 'center',
        justifyContent: 'center',
    },
    backBtnText:{
        fontSize: 16,
        fontWeight: '600',
        color: '#666',
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    modalContainer: {
        backgroundColor: '#fff',
        borderRadius: 12,
        paddingHorizontal: 24,
        paddingVertical: 28,
        width: '85%',
        maxWidth: 400,
    },
    modalHeader: {
        alignItems: 'center',
        marginBottom: 20,
        gap: 12,
    },
    modalTitle: {
        fontSize: 20,
        fontWeight: '700',
        color: '#000',
        textAlign: 'center',
    },
    modalLabel: {
        fontSize: 16,
        color: '#EF7810',
        marginBottom: 8,
        fontWeight: '500',
    },
    modalDescription: {
        fontSize: 16,
        color: '#666',
        marginBottom: 20,
        textAlign: 'center',
        lineHeight: 22,
    },
    modalInputGroup: {
        marginBottom: 16,
    },
    modalInput: {
        borderWidth: 1,
        borderColor: '#e0e0e0',
        borderRadius: 6,
        paddingHorizontal: 12,
        paddingVertical: 10,
        fontSize: 16,
        color: '#333',
    },
    modalButtons: {
        flexDirection: 'row',
        gap: 12,
        marginTop: 24,
    },
    modalConfirmButton: {
        flex: 1,
        paddingVertical: 12,
        borderColor: '#EF7810',
        backgroundColor: '#fff',
        borderWidth: 1,
        borderRadius: 6,
        alignItems: 'center',
    },
    modalConfirmButtonText: {
        fontSize: 18,
        fontWeight: '600',
        color: '#EF7810',
    },
    modalCancelButton: {
        flex: 1,
        paddingVertical: 12,
        borderWidth: 1,
        borderColor: '#d0d0d0',
        borderRadius: 6,
        alignItems: 'center',
    },
    modalCancelButtonText: {
        fontSize: 18,
        fontWeight: '600',
        color: '#666',
    },
    modalResultTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#333',
        textAlign: 'center',
        marginBottom: 12,
    },
    modalSingleButton: {
        marginTop: 24,
        paddingVertical: 12,
        borderColor: '#EF7810',
        backgroundColor: '#EF7810',
        borderWidth: 1,
        borderRadius: 6,
        alignItems: 'center',
    },
    modalSingleButtonText: {
        fontSize: 18,
        fontWeight: '600',
        color: '#fff',
    },
    genderContainer: {
        flexDirection: 'row',
        gap: 12,
    },
    genderButton: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 14,
        paddingHorizontal: 12,
        borderWidth: 0,
        borderRadius: 0,
        backgroundColor: 'transparent',
        gap: 10,
    },
    genderButtonActive: {
        backgroundColor: 'transparent',
    },
    genderButtonText: {
        fontSize: 14,
        fontWeight: '500',
        color: '#333',
    },
    genderButtonTextActive: {
        color: '#333',
    },
    genderRadioButton: {
        width: 20,
        height: 20,
        borderRadius: 10,
        borderWidth: 2,
        borderColor: '#ddd',
        justifyContent: 'center',
        alignItems: 'center',
    },
    genderRadioButtonActive: {
        borderColor: '#EF7810',
    },
    genderRadioButtonInner: {
        width: 10,
        height: 10,
        borderRadius: 5,
        backgroundColor: '#EF7810',
    },
    withdrawText: {
        fontSize: 16,
        color: 'red',
        fontWeight: '600',
    },
    passwordModal: {
        backgroundColor: "#fff",
        borderRadius: 8,
        width: "80%",
        paddingTop: 20,
        paddingHorizontal: 20,
    },
    modalContent: {
        marginBottom: 20,
    },
    passwordInput: {
        borderWidth: 1,
        borderColor: "#ddd",
        borderRadius: 4,
        paddingHorizontal: 12,
        paddingVertical: 10,
        fontSize: 14,
        color: "#000",
    },
    modalButtonContainer: {
        flexDirection: "row",
        gap: 8,
        paddingBottom: 20,
    },
    modalSubmitButton: {
        flex: 1,
        backgroundColor: "#EF7810",
        borderRadius: 4,
        paddingVertical: 10,
        alignItems: "center",
        justifyContent: "center",
    },
    modalSubmitButtonText: {
        fontSize: 14,
        fontWeight: "600",
        color: "#fff",
    },
});