import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#f8f8f8',
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        padding: 20,
        backgroundColor: '#fff',
    },
    backButton: {
        width: 44,
        height: 44,
        justifyContent: 'center',
        alignItems: 'flex-start',
    },
    title: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#333',
        position: 'absolute',
        left: 0,
        right: 0,
        textAlign: 'center',
        pointerEvents: 'none',
    },
    placeholder: {
        width: 40,
    },
    editButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 4,
        backgroundColor: '#fff',
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#EF7810',
    },
    editText: {
        fontSize: 14,
        color: '#EF7810',
        fontWeight: '700',
    },
    myInfoContainer: {
        flex: 1,
    },
    myInfoItemContainer: {
        paddingHorizontal: 16,
        paddingVertical: 12,
        backgroundColor: '#fff',
        marginVertical: 1,
    },
    myInfoContentContainer: {
        padding: 20,
        gap: 5,
    },
    sectionCard: {
        backgroundColor: '#fff',
        borderRadius: 12,
        padding: 16,
        marginBottom: 8,
        borderWidth: 1,
        borderColor: '#f0f0f0',
    },
    sectionInfoHeader:{
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    sectionHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 16,
        gap: 8,
    },
    sectionHeaderPressable: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 16,
        gap: 8,
        paddingVertical: 8,
        marginHorizontal: -16,
        paddingHorizontal: 16,
    },
    sectionTitleContainer:{
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    sectionTitle: {
        fontSize: 18,
        fontWeight: '600',
        color: '#EF7810',
    },
    infoContainer: {
        gap: 12,
    },
    infoRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 10,
        borderBottomWidth: 1,
        borderBottomColor: '#f0f0f0',
    },
    infoLabel: {
        fontSize: 16,
        color: '#666',
        fontWeight: '500',
    },
    infoValue: {
        fontSize: 16,
        color: '#333',
        fontWeight: '500',
    },
    socialButtonRow: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 12,
        gap: 12,
        borderBottomWidth: 1,
        borderBottomColor: '#f0f0f0',
    },
    socialButtonText: {
        fontSize: 16,
        color: '#333',
        fontWeight: '500',
    },
    myInfoItemText: {
        fontSize: 20,
        color: '#EF7810',
        marginBottom: 8,
    },
    myInfoSocialContainer: {
        flexDirection: 'row',
        gap: 12,
    },
    myInfoSocialButton: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    myInfoSocialButtonText: {
        fontSize: 16,
        color: '#333',
    },
    myInfoTextContainer: {
        gap: 10,
    },
    giftinfoContainer: {
        gap: 12,
        flexDirection: 'row',
    },
    giftImage: {
        width: 80,
        height: 80,
        marginBottom: 8,
    },
    giftBox: {
        padding: 5,
        justifyContent: 'center',
        alignItems: 'center',
    },
    myInfoText: {
        flex: 1,
        paddingHorizontal: 12,
        paddingVertical: 10,
        fontSize: 18,
        color: 'rgb(0, 0, 0)',
        backgroundColor: '#fff',
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    modalContent: {
        backgroundColor: '#fff',
        borderRadius: 12,
        paddingHorizontal: 24,
        paddingVertical: 28,
        width: '85%',
        maxWidth: 400,
    },
    modalTitle: {
        fontSize: 20,
        fontWeight: '700',
        color: '#000',
        marginBottom: 24,
        textAlign: 'center',
    },
    modalInputSection: {
        marginBottom: 18,
    },
    modalText: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#EF7810',
        marginBottom: 8,
    },
    modalPasswordHint: {
        fontSize: 16,
        color: '#999',
        marginTop: 6,
    },
    modalTextInput: {
        marginTop: 4,
        borderWidth: 1,
        borderColor: '#e0e0e0',
        borderRadius: 6,
        paddingHorizontal: 12,
        paddingVertical: 10,
        fontSize: 16,
        color: '#919191ff',
        backgroundColor: '#fff',
    },
    modalButtonContainer: {
        flexDirection: 'row',
        gap: 12,
        marginTop: 24,
    },
    modalCancelButton: {
        flex: 1,
        paddingVertical: 12,
        borderWidth: 1,
        borderColor: '#d0d0d0',
        borderRadius: 6,
        alignItems: 'center',
    },
    modalCancelButtonText: {
        fontSize: 18,
        fontWeight: '600',
        color: '#666',
    },
    modalConfirmButton: {
        flex: 1,
        paddingVertical: 12,
        borderColor: '#EF7810',
        backgroundColor: '#fff',
        borderWidth: 1,
        borderRadius: 6,
        alignItems: 'center',
    },
    modalConfirmButtonText: {
        fontSize: 18,
        fontWeight: '600',
        color: '#EF7810',
    },
    securityButton: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 12,
        gap: 12,
        borderBottomWidth: 1,
        borderBottomColor: '#f0f0f0',
    },
    securityButtonText: {
        fontSize: 16,
        color: '#333',
        fontWeight: '500',
    },
    modalContainer: {
        backgroundColor: '#fff',
        borderRadius: 12,
        paddingHorizontal: 24,
        paddingVertical: 28,
        width: '85%',
        maxWidth: 400,
    },
    modalHeader: {
        alignItems: 'center',
        marginBottom: 20,
        gap: 12,
    },
    modalLabel: {
        fontSize: 16,
        color: '#EF7810',
        marginBottom: 8,
        fontWeight: '500',
    },
    modalDescription: {
        fontSize: 16,
        color: '#666',
        marginBottom: 20,
        textAlign: 'center',
        lineHeight: 22,
    },
    modalInputGroup: {
        marginBottom: 16,
    },
    modalInput: {
        borderWidth: 1,
        borderColor: '#e0e0e0',
        borderRadius: 6,
        paddingHorizontal: 12,
        paddingVertical: 10,
        fontSize: 16,
        color: '#333',
    },
    modalButtons: {
        flexDirection: 'row',
        gap: 12,
        marginTop: 24,
    },
    modalResultTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#333',
        textAlign: 'center',
        marginBottom: 12,
    },
    modalSingleButton: {
        marginTop: 24,
        paddingVertical: 12,
        borderColor: '#EF7810',
        backgroundColor: '#EF7810',
        borderWidth: 1,
        borderRadius: 6,
        alignItems: 'center',
    },
    modalSingleButtonText: {
        fontSize: 18,
        fontWeight: '600',
        color: '#fff',
    },
});
