import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#ffffffff',
    },
    myInfoContainer: {
        flex: 1,
        paddingLeft: 10
    },
    headerContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 16,
        paddingVertical: 12,
        backgroundColor: '#fff',
        borderBottomWidth: 1,
        borderBottomColor: '#f0f0f0',
    },
    headerBackButton: {
        paddingRight: 12,
    },
    headerBackButtonText: {
        fontSize: 24,
        color: '#000',
    },
    headerTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: '#000',
        flex: 1,
        textAlign: 'center',
    },
    myInfoItemContainer: {
        paddingHorizontal: 16,
        paddingVertical: 12,
        backgroundColor: '#fff',
        marginVertical: 1,
    },
    myInfoItemText: {
        fontSize: 13,
        color: '#EF7810',
        marginBottom: 8,
    },
    myInfoInputContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
    },
    myInfoTextInput: {
        flex: 1,
        borderWidth: 1,
        borderColor: '#f0f0f0',
        borderRadius: 6,
        paddingHorizontal: 12,
        paddingVertical: 10,
        fontSize: 14,
        color: '#919191ff',
        backgroundColor: '#fff',
    },
    myInfoPwChangeButton: {
        paddingVertical: 10,
        paddingHorizontal: 14,
        borderWidth: 1,
        borderColor: '#EF7810',
        backgroundColor: '#fff',
        borderRadius: 6,
    },
    myInfoPwChangeButtonText: {
        fontSize: 13,
        color: '#EF7810',
    },
    myInfoVerifyButton: {
        paddingVertical: 10,
        paddingHorizontal: 14,
        borderWidth: 1,
        borderColor: '#EF7810',
        backgroundColor: '#fff',
        borderRadius: 6,
    },
    myInfoVerifyButtonText: {
        fontSize: 13,
        color: '#EF7810',
    },
    myInfoRadioContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 20,
        marginTop: 10,
    },
    myInfoRadioButton: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    myInfoRadioButtonCircle: {
        width: 16,
        height: 16,
        borderRadius: 8,
        borderWidth: 2,
        borderColor: '#d0d0d0',
    },
    myInfoRadioButtonCircleActive: {
        width: 16,
        height: 16,
        borderRadius: 8,
        backgroundColor: '#000',
    },
    myInfoRadioButtonText: {
        fontSize: 14,
        color: '#5b5b5bff',
    },
    myInfoCategoryContainer: {
        marginTop: 10,
    },
    myInfoCategoryButton: {
        flexDirection: 'row',
        paddingVertical: 10,
        paddingHorizontal: 12,
        backgroundColor: '#f0f0f0',
        borderRadius: 6,
        marginRight: 8,
        marginBottom: 8,
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    myInfoCategoryButtonText: {
        fontSize: 13,
        color: '#555555ff',
    },
    myInfoCategoryButtonArrow: {
        fontSize: 14,
        color: '#999',
        marginLeft: 8,
    },
    myInfoSaveButton: {
        marginHorizontal: 16,
        marginVertical: 20,
        paddingVertical: 14,
        borderWidth: 1,
        borderColor: '#EF7810',
        backgroundColor: '#ffffff',
        borderRadius: 6,
        alignItems: 'center',
    },
    myInfoSaveButtonText: {
        fontSize: 15,
        color: '#EF7810',
        fontWeight: '600',
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    modalContent: {
        backgroundColor: '#fff',
        borderRadius: 12,
        paddingHorizontal: 24,
        paddingVertical: 28,
        width: '85%',
        maxWidth: 400,
    },
    modalTitle: {
        fontSize: 16,
        fontWeight: '700',
        color: '#000',
        marginBottom: 24,
        textAlign: 'center',
    },
    modalInputSection: {
        marginBottom: 18,
    },
    modalLabel: {
        fontSize: 13,
        color: '#EF7810',
        marginBottom: 8,
    },
    modalPasswordHint:{
        fontSize: 10,
        color: '#999',
        marginTop: 6,
    },
    modalTextInput: {
        borderWidth: 1,
        borderColor: '#e0e0e0',
        borderRadius: 6,
        paddingHorizontal: 12,
        paddingVertical: 10,
        fontSize: 14,
        color: '#919191ff',
        backgroundColor: '#fff',
    },
    categoryText:{
        fontSize: 13,
    },
    modalButtonContainer: {
        flexDirection: 'row',
        gap: 12,
        marginTop: 24,
    },
    modalCancelButton: {
        flex: 1,
        paddingVertical: 12,
        borderWidth: 1,
        borderColor: '#d0d0d0',
        borderRadius: 6,
        alignItems: 'center',
    },
    modalCancelButtonText: {
        fontSize: 14,
        fontWeight: '600',
        color: '#666',
    },
    modalConfirmButton: {
        flex: 1,
        paddingVertical: 12,
        borderColor: '#EF7810',
        backgroundColor: '#fff',
        borderWidth: 1,
        borderRadius: 6,
        alignItems: 'center',
    },
    modalConfirmButtonText: {
        fontSize: 14,
        fontWeight: '600',
        color: '#EF7810',
    },
});