import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#ffffff",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: 20,
    backgroundColor: "#fff",
  },
  backButton: {
    width: 44,
    height: 44,
    justifyContent: "center",
    alignItems: "flex-start",
  },
  title: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#333",
    position: "absolute",
    left: 0,
    right: 0,
    textAlign: "center",
    pointerEvents: "none",
  },
  placeholder: {
    width: 40,
  },

  productDetailContainer: {
    flex: 1,
    backgroundColor: "#fff",
  },
  productImage: {
    width: "100%",
    height: 350,
    backgroundColor: "#f8f8f8",
  },
  productDetailInfoContainer: {
    padding: 20,
    backgroundColor: "#fff",
  },
  storeNameContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    borderBottomWidth: 1,
    borderBottomColor: "#eee",
    marginBottom: 12,
  },
  storeName: {
    fontSize: 14,
    color: "#666",
    marginBottom: 8,
  },
  subInfoContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  categoryText: {
    fontSize: 14,
    color: "#666",
  },
  tagRow: {
    flexDirection: "row",
    gap: 6,
    marginTop: 4,
  },
  negoTag: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: "#FFD700",
    backgroundColor: "#fff",
  },
  negoTagText: {
    fontSize: 12,
    color: "#FFD700",
    fontWeight: "500",
  },
  discountTag: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: "#4285F4",
    backgroundColor: "#fff",
  },
  discountTagText: {
    fontSize: 12,
    color: "#4285F4",
    fontWeight: "500",
  },
  adultTag: {
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: "#FF4444",
    backgroundColor: "#fff",
    width: 35,
    justifyContent: "center",
    alignItems: "center",
  },
  adultTagText: {
    fontSize: 12,
    color: "#FF4444",
    fontWeight: "500",
  },
  nameContainer: {
    marginBottom: 10,
    gap: 3,
  },
  productName: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#333",
  },
  iconButton: {
    padding: 4,
  },
  priceAndStockContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  priceContainer: {
    flex: 1,
  },
  originalPrice: {
    fontSize: 14,
    color: "#999",
    textDecorationLine: "line-through",
  },
  discountPriceContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  discountPrice: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#333",
  },
  discountRate: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#EF7810",
  },
  stockContainer: {
    justifyContent: "center",
  },
  stockText: {
    fontSize: 14,
    color: "#777",
  },
  ratingContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  ratingText: {
    fontSize: 14,
    color: "#777",
    marginLeft: 4,
  },
  tabsContainer: {
    flex: 1,
    borderTopWidth: 8,
    borderTopColor: "#f5f5f5",
    backgroundColor: "#fff",
  },
  tabs: {
    flexDirection: "row",
    backgroundColor: "#fff",
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
  },
  tab: {
    flex: 1,
    paddingVertical: 16,
    alignItems: "center",
    borderBottomWidth: 3,
    borderBottomColor: "transparent",
    backgroundColor: "#fff",
  },
  activeTab: {
    borderBottomColor: "#EF7810",
  },
  tabText: {
    fontSize: 15,
    fontWeight: "500",
    color: "#999",
  },
  activeTabText: {
    color: "#EF7810",
    fontWeight: "700",
  },
  tabContentContainer: {
    flex: 1,
    padding: 20,
    backgroundColor: "#fafafa",
  },
  tabContent: {
    fontSize: 14,
    color: "#333",
    lineHeight: 24,
  },
  descriptionContent: {
    flex: 1,
  },
  detailsContent: {
    flex: 1,
  },
  reviewsContent: {
    flex: 1,
  },
  reviewItem: {
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#f0f0f0",
  },
  reviewHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 4,
  },
  reviewUserName: {
    fontSize: 14,
    fontWeight: "600",
    color: "#333",
  },
  reviewRating: {
    flexDirection: "row",
    gap: 2,
  },
  reviewDate: {
    fontSize: 12,
    color: "#999",
    marginBottom: 8,
  },
  reviewContent: {
    fontSize: 14,
    color: "#555",
    lineHeight: 20,
  },
  detailRow: {
    flexDirection: "row",
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#f0f0f0",
  },
  detailLabel: {
    width: 100,
    fontSize: 14,
    fontWeight: "600",
    color: "#666",
  },
  detailValue: {
    flex: 1,
    fontSize: 14,
    color: "#333",
  },
  actionButtonsContainer: {
    flexDirection: "row",
    gap: 12,
    padding: 16,
    backgroundColor: "#fff",
    borderTopWidth: 1,
    borderTopColor: "#f0f0f0",
  },
  cartButton: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: "#fff",
    borderWidth: 2,
    borderColor: "#EF7810",
    justifyContent: "center",
    alignItems: "center",
  },
  purchaseButton: {
    flex: 1,
    height: 40,
    borderRadius: 12,
    backgroundColor: "#EF7810",
    justifyContent: "center",
    alignItems: "center",
  },
  purchaseButtonText: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#fff",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  negoModalContent: {
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: 24,
    width: "85%",
    maxWidth: 340,
    elevation: 5,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  negoModalTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#1F2937",
    marginBottom: 20,
    textAlign: "center",
  },
  negoModalLabel: {
    fontSize: 14,
    fontWeight: "600",
    color: "#374151",
    marginBottom: 8,
  },
  negoInput: {
    borderWidth: 1,
    borderColor: "#D1D5DB",
    borderRadius: 8,
    padding: 12,
    fontSize: 16,
    color: "#1F2937",
    backgroundColor: "#fff",
  },
  negoAmountDisplay: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#EF7810",
    marginTop: 12,
    marginBottom: 20,
    textAlign: "right",
  },
  negoModalButtons: {
    flexDirection: "row",
    gap: 12,
    marginTop: 24,
  },
  negoModalButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 8,
    alignItems: "center",
  },
  negoConfirmButton: {
    backgroundColor: "#EF7810",
  },
  negoConfirmButtonText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#fff",
  },
  negoCancelButton: {
    backgroundColor: "#F3F4F6",
  },
  negoCancelButtonText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#4B5563",
  },
});
