import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#F8F9FA',
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 20,
        paddingVertical: 16,
        backgroundColor: '#fff',
        borderBottomWidth: 1,
        borderBottomColor: '#F0F0F0',
    },
    backButton: {
        width: 44,
        height: 44,
        justifyContent: 'center',
        alignItems: 'flex-start',
    },
    title: {
        fontSize: 20,
        fontWeight: '700',
        color: '#1A1A1A',
        position: 'absolute',
        left: 0,
        right: 0,
        textAlign: 'center',
        pointerEvents: "none"
    },
    placeholder: {
        width: 40,
    },
    noticeDetailHeaderContainer: {
        backgroundColor: '#FFFFFF',
        marginHorizontal: 16,
        marginTop: 16,
        marginBottom: 12,
        padding: 20,
        borderRadius: 16,
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.06,
        shadowRadius: 8,
        elevation: 3,
    },
    noticeDetailTitleText: {
        fontSize: 20,
        fontWeight: '700',
        color: '#1A1A1A',
        marginBottom: 12,
        lineHeight: 28,
    },
    noticeDetailDateText: {
        fontSize: 13,
        color: '#8E8E93',
        fontWeight: '400',
    },
    noticeDetailContentContainer: {
        backgroundColor: '#FFFFFF',
        marginHorizontal: 16,
        marginBottom: 16,
        padding: 20,
        borderRadius: 16,
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.06,
        shadowRadius: 8,
        elevation: 3,
    },
    noticeDetailContentText: {
        fontSize: 15,
        lineHeight: 24,
        color: '#333333',
        marginBottom: 20,
        letterSpacing: -0.2,
    },
    noticeDetailImageContainer: {
        width: '100%',
        height: 200,
        borderRadius: 12,
        backgroundColor: '#F5F5F5',
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 20,
        overflow: 'hidden',
    },
    noticeDetailFileContainer: {
        alignItems: 'center',
        flexDirection: 'row',
        paddingHorizontal: 16,
        paddingVertical: 14,
        backgroundColor: '#FFF9F0',
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#FFE8CC',
        justifyContent: 'space-between',
    },
    noticeDetailFileItemContainer: {
        flex: 1,
        marginRight: 12,
    },
    noticeDetailFileText: {
        fontSize: 14,
        fontWeight: '600',
        color: '#1A1A1A',
        marginBottom: 4,
    },
    noticeDetailFileSizeText: {
        fontSize: 12,
        color: '#8E8E93',
    },
    downloadIcon: {
        padding: 4,
    },
    pinnedBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#EF7810',
        paddingHorizontal: 10,
        paddingVertical: 5,
        borderRadius: 8,
        marginBottom: 12,
        alignSelf: 'flex-start',
    },
    pinnedBadgeText: {
        fontSize: 12,
        fontWeight: '700',
        color: '#FFFFFF',
        marginLeft: 4,
    },
});