import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#ffffff',
    },
    headerContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        padding: 20,
        backgroundColor: '#fff',
    },
    backButton: {
        width: 44,
        height: 44,
        justifyContent: 'center',
        alignItems: 'flex-start',
    },
    title: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#333',
        position: 'absolute',
        left: 0,
        right: 0,
        textAlign: 'center',
        pointerEvents: "none"
    },
    placeholder: {
        width: 40,
    },
    searchTopContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 16,
        paddingVertical: 10,
    },
    searchText: {
        fontSize: 16,
        color: '#999',
        paddingHorizontal: 10,
        borderWidth: 1,
        borderColor: 'rgba(0, 0, 0, 0.2)',
        borderRadius: 5,
        alignItems: "center",
        justifyContent: "center",
        width: 300,
        height: 40,
        borderBottomWidth: 1,
        opacity: 1,
        flex: 1,
    },
    searchTextFocused: {
        borderColor: '#EF781066',
        backgroundColor: '#fff',
    },
    searchButton: {
        borderWidth: 1,
        borderRadius: 5,
        borderColor: "#EF7810",
        marginLeft: 10,
        height: 40,
        justifyContent: "center",
        alignItems: "center",
    },
    searchButtonText: {
        fontSize: 18,
        paddingHorizontal: 25,
        color: "#EF7810",
    },
    filterContainer: {
        flexDirection: 'row',
        paddingHorizontal: 16,
        gap: 12,
    },
    selectBox: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 5,
        paddingHorizontal: 8,
        borderWidth: 1,
        borderColor: '#ddd',
        borderRadius: 6,
        backgroundColor: '#fff',
    },
    selectBoxText: {
        fontSize: 18,
        fontWeight: '500',
        color: '#666',
    },
    listContainer: {
        paddingHorizontal: 16,
        paddingTop: 12,
        paddingBottom: 100,
    },
    orderContainer: {
        backgroundColor: '#fff',
        borderRadius: 8,
        marginBottom: 12,
        padding: 12,
    },
    orderDateContainer: {
        paddingBottom: 12,
        borderBottomWidth: 1,
        borderBottomColor: '#f0f0f0',
        marginBottom: 12,
    },
    orderTopContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 3,
        paddingVertical: 8,
        borderBottomWidth: 1,
        borderBottomColor: '#f0f0f0',
    },
    orderDate: {
        fontSize: 16,
        fontWeight: '600',
        color: '#333',
    },
    orderItemContainer: {
        borderWidth: 1,
        borderColor: '#f0f0f0',
        borderRadius: 8,
        backgroundColor: '#fff',
        padding: 16,
        marginBottom: 8,
    },
    topInfoRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 0,
    },
    orderState: {
        fontSize: 13,
        color: '#EF7810',
        fontWeight: '600',
    },
    orderDetailButton: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 2,
        paddingVertical: 3,
        paddingHorizontal: 6,
        borderWidth: 1,
        borderColor: '#ddd',
        borderRadius: 4,
    },
    orderDetailButtonText: {
        fontSize: 12,
        color: '#666',
    },
    orderProductInfoContainer: {
        flexDirection: 'row',
        paddingHorizontal: 16,
        gap: 12,
        alignItems: 'stretch',
    },
    orderProductImgContainer: {
        width: 80,
        borderWidth: 1,
        borderColor: '#cfcfcfff',
        borderRadius: 6,
        justifyContent: 'center',
        alignItems: 'center',
    },
    orderProductDetailContainer: {
        flex: 1,
        justifyContent: 'space-between',
    },
    productName: {
        fontSize: 16,
        fontWeight: '600',
        color: '#000',
        marginBottom: 8,
    },
    bottomInfoRow: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    productPrice: {
        fontSize: 18,
        fontWeight: '600',
        color: '#000',
    },
    separator: {
        fontSize: 14,
        color: '#999',
    },
    productDate: {
        fontSize: 14,
        color: '#999',
    },
    modalOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        zIndex: 999,
    },
    modalContentWrapper: {
        flex: 1,
        justifyContent: 'flex-end',
    },
    filterModalContent: {
        backgroundColor: '#fff',
        borderTopLeftRadius: 16,
        borderTopRightRadius: 16,
        padding: 16,
        maxHeight: '80%',
        width: '100%',
    },
    filterModalCloseButton: {
        fontSize: 20,
        color: '#666',
    },
    filterSection: {
        marginBottom: 24,
    },
    filterSectionTitle: {
        fontSize: 20,
        fontWeight: '600',
        marginBottom: 12,
    },
    filterOptionButtonText: {
        fontSize: 18,
        color: '#333',
    },
    filterOptions: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 8,
    },
    filterOptionButton: {
        paddingVertical: 8,
        paddingHorizontal: 16,
        borderWidth: 1,
        borderColor: '#ddd',
        borderRadius: 6,
        backgroundColor: '#ffffffff',
    },
    filterOptionButtonActive: {
        borderColor: '#EF7810',
        backgroundColor: '#fff5f0',
    },
    filterDateOptions: {
        gap: 8,
    },
    filterDateButton: {
        paddingVertical: 12,
        paddingHorizontal: 16,
        borderWidth: 1,
        borderColor: '#ddd',
        borderRadius: 6,
        backgroundColor: '#ffffffff',
    },
    filterDateButtonActive: {
        borderColor: '#EF7810',
        backgroundColor: '#fff5f0',
    },
    applyButton: {
        paddingVertical: 14,
        borderWidth: 1,
        borderColor: '#EF7810',
        backgroundColor: '#ffffffff',
        borderRadius: 8,
        alignItems: 'center',
        marginTop: 24,
    },
    applyButtonText: {
        color: '#EF7810',
        fontSize: 20,
        fontWeight: '600',
    },
    modalContent: {
        backgroundColor: '#fff',
        borderRadius: 8,
        padding: 16,
        minWidth: 200,
    },
    modalItem: {
        paddingVertical: 12,
        paddingHorizontal: 16,
        fontSize: 16,
    },
    scrollToTopButton: {
        position: 'absolute',
        right: 20,
        width: 60,
        height: 60,
        borderRadius: 30,
        backgroundColor: '#EF7810',
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.2,
        shadowRadius: 6,
        elevation: 5,
    },
    scrollToTopButtonText: {
        fontSize: 20,
        color: '#fff',
        fontWeight: '700',
    },
});
