import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#f8f8f8",
    },
    header: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        padding: 20,
        backgroundColor: "#fff",
    },
    backButton: {
        width: 44,
        height: 44,
        justifyContent: "center",
        alignItems: "flex-start",
    },
    title: {
        fontSize: 18,
        fontWeight: "bold",
        color: "#333",
        position: "absolute",
        left: 0,
        right: 0,
        textAlign: "center",
        pointerEvents: "none",
    },
    placeholder: {
        width: 40,
    },
    content: {
        flex: 1,
        padding: 16,
    },
    section: {
        marginBottom: 20,
    },
    sectionTitle: {
        fontSize: 16,
        fontWeight: "700",
        color: "#333",
        marginBottom: 12,
    },
    paymentCard: {
        backgroundColor: "#fff",
        borderRadius: 12,
        padding: 16,
        marginBottom: 8,
        borderWidth: 1,
        borderColor: "#f0f0f0",
    },
    paymentCardSelected: {
        borderColor: "#EF7810",
        backgroundColor: "#fffaf5",
    },
    paymentCardContent: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
    },
    paymentCardLeft: {
        flexDirection: "row",
        alignItems: "center",
        flex: 1,
        gap: 12,
    },
    cardIconContainer: {
        width: 48,
        height: 48,
        borderRadius: 8,
        backgroundColor: "#fff3e0",
        justifyContent: "center",
        alignItems: "center",
    },
    paymentCardInfo: {
        flex: 1,
    },
    paymentCardType: {
        fontSize: 16,
        fontWeight: "600",
        color: "#333",
        marginBottom: 4,
    },
    paymentCardNumber: {
        fontSize: 14,
        color: "#999",
    },
    actionButtons: {
        flexDirection: "row",
        gap: 8,
        marginTop: 12,
        paddingTop: 12,
        borderTopWidth: 1,
        borderTopColor: "#f0f0f0",
    },
    actionButton: {
        flex: 1,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        gap: 6,
        paddingVertical: 10,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: "#fff",
        backgroundColor: "#EF7810",
    },
    deleteButton: {
        borderColor: "#ef4444",
    },
    actionButtonText: {
        fontSize: 14,
        fontWeight: "600",
        color: "#fff",
    },
    deleteButtonText: {
        color: "#fff",
    },
    emptyContainer: {
        alignItems: "center",
        justifyContent: "center",
        paddingVertical: 40,
        backgroundColor: "#fff",
        borderRadius: 12,
    },
    emptyText: {
        fontSize: 14,
        color: "#999",
        marginTop: 12,
    },
    addButton: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        gap: 8,
        backgroundColor: "#EF7810",
        paddingVertical: 14,
        marginHorizontal: 16,
        marginBottom: 16,
        borderRadius: 8,
    },
    addButtonText: {
        fontSize: 16,
        fontWeight: "700",
        color: "#fff",
    },
});
