import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#fff',
    },
    headerContainer: {
        width: '100%',
        backgroundColor: '#fff',
        height: 56,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        position: 'relative',
    },
    backButton: {
        position: 'absolute',
        left: 16,
        padding: 8,
    },
    headerTitleText: {
        fontSize: 18,
        fontWeight: '600',
    },
    productDetailImgContainer: {
        width: '100%',
        height: 220,
        justifyContent: 'center',
        borderWidth: 1,
        borderColor: '#cfcfcfff',
        alignItems: 'center',
    },
    productDetailInfoTopContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 16,
        paddingVertical: 12,
        gap: 12,
    },
    productDetailIconContainer: {
        width: 50,
        height: 50,
        backgroundColor: '#f5f5f5',
        borderRadius: 8,
        justifyContent: 'center',
        alignItems: 'center',
        fontSize: 28,
    },
    productDetailAddressContainer: {
        flex: 1,
    },
    productDetailNameText: {
        fontSize: 13,
        color: '#999',
        marginBottom: 4,
    },
    productSaleRateText: {
        fontSize: 13,
        color: '#EF7810',
        lineHeight: 18,
    },
    productDetailPriceContainer: {
        marginTop: 4,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
    },
    productSalePriceText: {
        fontSize: 13,
        color: '#999',
        lineHeight: 18,
        textDecorationLine: 'line-through',
    },
    productLeftQuantityText: {
        fontSize: 13,
        color: '#333',
        lineHeight: 18,
    },
    productDetailMapContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    productDetailAddrDetailText: {
        fontSize: 14,
        fontWeight: '600',
        color: '#000',
    },
    mapIconText: {
        fontSize: 16,
    },
    productDetailShareContainer: {
        paddingHorizontal: 8,
        paddingVertical: 6,
    },
    iconText: {
        fontSize: 12,
        color: '#666',
    },
    productDetailWishContainer: {
        paddingHorizontal: 8,
        paddingVertical: 6,
    },
    heartText: {
        fontSize: 18,
    },
    productDetailMoreContainer: {
        paddingHorizontal: 8,
        paddingVertical: 6,
    },
    moreText: {
        fontSize: 16,
        color: '#666',
    },
    productDetailRateInfoContainer: {
        flexDirection: 'row',
        paddingHorizontal: 16,
        borderBottomWidth: 1,
        borderBottomColor: '#f0f0f0',
    },
    rateText: {
        fontSize: 14,
        fontWeight: '600',
        color: '#000',
        marginBottom: 12,
    },
    productDetailNmContainer: {
        paddingHorizontal: 16,
        paddingVertical: 5,
    },
    productNmText: {
        fontSize: 15,
        color: '#000000ff',
        lineHeight: 18,
        fontWeight: '600',
        marginBottom: 5,
    },
    productPriceText: {
        fontSize: 15,
        color: '#000000ff',
        lineHeight: 18,
        fontWeight: '600',

    },
    tabContainer: {
        flexDirection: 'row',
        borderBottomWidth: 1,
        borderBottomColor: '#f0f0f0',
        paddingHorizontal: 16,
    },
    tabButton: {
        flex: 1,
        paddingVertical: 14,
        alignItems: 'center',
        borderBottomWidth: 2,
        borderBottomColor: 'transparent',
    },
    tabButtonActive: {
        borderBottomColor: '#EF7810',
    },
    tabText: {
        fontSize: 14,
        color: '#999',
        fontWeight: '500',
    },
    tabTextActive: {
        color: '#EF7810',
        fontWeight: '600',
    },
    productDetailProductInfoText: {
        fontSize: 13,
        color: '#333',
    },
    reviewContainer: {
        paddingHorizontal: 16,
        paddingVertical: 32,
        alignItems: 'center',
    },
    reviewText: {
        fontSize: 14,
        color: '#999',
    },
    productDetailReviewContainer: {
        paddingHorizontal: 16,
        paddingVertical: 16,
    },
    reviewItemContainer: {
        backgroundColor: '#fff',
        borderRadius: 8,
        padding: 12,
        marginBottom: 12,
        borderWidth: 1,
        borderColor: '#f0f0f0',
    },
    reviewRefInfoContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 8,
    },
    reviewRegNmContainer: {
        fontSize: 13,
        fontWeight: '600',
        color: '#000',
    },
    reviewRegDateContainer: {
        fontSize: 12,
        color: '#999',
    },
    reviewRateContainer: {
        fontSize: 12,
        color: '#ff9800',
        fontWeight: '600',
        marginBottom: 8,
    },
    reviewImgContainer: {
        width: '100%',
        height: 80,
        borderRadius: 6,
        borderWidth: 1,
        borderColor: '#f0f0f0',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 8,
    },
    reviewContentContainer: {
        fontSize: 12,
        color: '#666',
        lineHeight: 16,
    },
    productDetailProductContainer: {
        paddingHorizontal: 16,
        paddingVertical: 16,
    },
    productGridContainer: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
    },
    productDetailProductItemContainer: {
        width: '48%',
        height: 250,
        backgroundColor: '#fff',
    },
    productDetailProductImgContainer: {
        width: '100%',
        height: 140,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#f0f0f0',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 8,
    },
    productDetailProductNmContainer: {
        fontSize: 12,
        color: '#333',
        lineHeight: 16,
    },
    productDetailProductPriceContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
    },
    salePercentText: {
        fontSize: 12,
        fontWeight: '600',
        color: '#ff6b6b',
    },
    priceText: {
        fontSize: 12,
        fontWeight: '600',
        color: '#000',
    },
    ratingText: {
        fontSize: 11,
        color: '#999',
        lineHeight: 15,
    },
    productDetailTabContainer: {
        paddingHorizontal: 16,
        paddingVertical: 16,
    },
    productDetailTabText: {
        fontSize: 13,
        color: '#333',
        lineHeight: 18,
    },
    screenContainer: {
        flex: 1,
        position: 'relative',
    },
    scrollToTopButton: {
        position: 'absolute',
        bottom: 20,
        right: 20,
        width: 32,
        height: 32,
        borderRadius: 16,
        backgroundColor: '#EF7810',
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.2,
        shadowRadius: 6,
        elevation: 5,
    },
    scrollToTopButtonText: {
        fontSize: 10,
        color: '#fff',
        fontWeight: '700',
    },
});