import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#fff',
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        padding: 20,
        backgroundColor: '#fff',
    },
    backButton: {
        width: 44,
        height: 44,
        justifyContent: 'center',
        alignItems: 'flex-start',
    },
    title: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#333',
        position: 'absolute',
        left: 0,
        right: 0,
        textAlign: 'center',
        pointerEvents: "none"
    },
    placeholder: {
        width: 40,
    },
    storeImgContainer: {
        width: '100%',
        height: 280,
        justifyContent: 'center',
        borderWidth: 1,
        borderColor: '#cfcfcfff',
        alignItems: 'center',
    },
    actionButtonsRow: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        paddingVertical: 12,
        paddingHorizontal: 16,
        borderBottomWidth: 1,
        borderBottomColor: '#f0f0f0',
        backgroundColor: '#fff',
    },
    actionButton: {
        alignItems: 'center',
        gap: 6,
        paddingVertical: 4,
        paddingHorizontal: 12,
    },
    actionButtonText: {
        fontSize: 14,
        color: '#666',
        fontWeight: '500',
    },
    storeInfoContainer: {
        paddingHorizontal: 16,
        paddingVertical: 12,
        borderBottomWidth: 1,
        borderBottomColor: '#f0f0f0',
        gap: 10,
    },
    storeNameRatingRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
    },
    storeNameText: {
        fontSize: 20,
        fontWeight: '700',
        color: '#000',
    },
    ratingContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
    },
    descriptionContainer: {
        backgroundColor: '#f8f8f8',
        paddingHorizontal: 12,
        paddingVertical: 10,
        borderRadius: 8,
    },
    descriptionText: {
        fontSize: 14,
        color: '#666',
        lineHeight: 20,
    },
    addressRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
        paddingVertical: 4,
    },
    addressText: {
        flex: 1,
        fontSize: 14,
        color: '#666',
    },
    tabContainer: {
        flexDirection: 'row',
        borderBottomWidth: 1,
        borderBottomColor: '#f0f0f0',
        paddingHorizontal: 16,
    },
    tabButton: {
        flex: 1,
        paddingVertical: 14,
        alignItems: 'center',
        borderBottomWidth: 2,
        borderBottomColor: 'transparent',
    },
    tabButtonActive: {
        borderBottomColor: '#EF7810',
    },
    tabText: {
        fontSize: 16,
        color: '#999',
        fontWeight: '500',
    },
    tabTextActive: {
        color: '#EF7810',
        fontWeight: '600',
    },
    storeReviewContainer: {
        paddingHorizontal: 16,
        paddingVertical: 16,
    },
    reviewItemContainer: {
        backgroundColor: '#fff',
        borderRadius: 8,
        padding: 12,
        marginBottom: 12,
        borderWidth: 1,
        borderColor: '#f0f0f0',
    },
    reviewHeaderRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 10,
    },
    reviewUserRatingContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    reviewRegNmText: {
        fontSize: 15,
        fontWeight: '600',
        color: '#000',
    },
    reviewRatingBox: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 3,
    },
    reviewRateText: {
        fontSize: 13,
        color: '#999',
        lineHeight: 18,
    },
    reviewRegDateText: {
        fontSize: 12,
        color: '#999',
    },
    reviewContentContainer: {
        backgroundColor: '#f8f8f8',
        padding: 12,
        borderRadius: 8,
        marginBottom: 10,
    },
    reviewContentText: {
        fontSize: 14,
        color: '#333',
        lineHeight: 20,
    },
    reviewImgGallery: {
        flexDirection: 'row',
        gap: 8,
        flexWrap: 'wrap',
    },
    reviewImgThumbnail: {
        width: 70,
        height: 70,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#e0e0e0',
    },
    storeProductContainer: {
        paddingHorizontal: 10,
    },
    productGridContainer: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 8,
    },
    storeProductItemContainer: {
        width: '48%',
        backgroundColor: '#fff',
        justifyContent: 'flex-start',
        overflow: 'hidden',
        borderRadius: 8,
        elevation: 2,
        marginBottom: 5,
        paddingVertical: 12,
    },
    storeProductImgContainer: {
        width: 180,
        height: 140,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#f0f0f0',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 10,
    },
    storeProductNmText: {
        fontSize: 14,
        color: '#333',
        marginBottom: 2,
        fontWeight: '600',
    },
    originalPriceText: {
        fontSize: 13,
        textDecorationLine: 'line-through',
        color: '#999',
        marginBottom: 2,
    },
    priceText: {
        fontSize: 17,
        fontWeight: '700',
        color: '#000',
        marginBottom: 4,
    },
    storeRatingText: {
        fontSize: 14,
        fontWeight: '600',
        color: '#999',
    },
    productRatingText: {
        fontSize: 13,
        color: '#999',
        lineHeight: 18,
    },
});