import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#ffffff",
    },
    header: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        padding: 20,
        backgroundColor: "#fff",
    },
    backButton: {
        width: 44,
        height: 44,
        justifyContent: "center",
        alignItems: "flex-start",
    },
    title: {
        fontSize: 18,
        fontWeight: "bold",
        color: "#333",
        position: "absolute",
        left: 0,
        right: 0,
        textAlign: "center",
        pointerEvents: "none",
    },
    placeholder: {
        width: 40,
    },
    content: {
        flex: 1,
        padding: 16,
    },
    section: {
        marginBottom: 24,
    },
    sectionTitle: {
        fontSize: 18,
        fontWeight: "600",
        color: "#000",
        marginBottom: 8,
    },
    description: {
        fontSize: 16,
        color: "#666",
        lineHeight: 18,
        marginBottom: 12,
    },
    reasonContainer: {
        backgroundColor: "#f9f9f9",
        borderRadius: 4,
        padding: 8,
    },
    reasonOption: {
        flexDirection: "row",
        alignItems: "center",
        paddingVertical: 12,
        paddingHorizontal: 8,
    },
    radioButton: {
        width: 20,
        height: 20,
        borderRadius: 10,
        borderWidth: 2,
        borderColor: "#ddd",
        justifyContent: "center",
        alignItems: "center",
        marginRight: 12,
    },
    radioButtonSelected: {
        borderColor: "#EF7810",
    },
    radioButtonInner: {
        width: 10,
        height: 10,
        borderRadius: 5,
        backgroundColor: "#EF7810",
    },
    reasonLabel: {
        fontSize: 16,
        color: "#666",
        flex: 1,
    },
    reasonLabelSelected: {
        color: "#000",
        fontWeight: "500",
    },
    detailSection: {
        marginTop: 16,
        paddingTop: 16,
        borderTopWidth: 1,
        borderTopColor: "#eee",
    },
    detailLabel: {
        fontSize: 16,
        fontWeight: "600",
        color: "#000",
        marginBottom: 8,
    },
    detailInput: {
        borderWidth: 1,
        borderColor: "#ddd",
        borderRadius: 4,
        padding: 12,
        fontSize: 14,
        color: "#000",
        backgroundColor: "#fff",
        minHeight: 100,
    },
    warningSection: {
        backgroundColor: "#fff3f0",
        borderRadius: 4,
        padding: 12,
        marginBottom: 24,
    },
    warningTitle: {
        fontSize: 16,
        fontWeight: "600",
        color: "#ef4444",
        marginBottom: 8,
    },
    warningText: {
        fontSize: 15,
        color: "#666",
        lineHeight: 18,
        marginBottom: 4,
    },
    bottomButtonContainer: {
        flexDirection: "row",
        gap: 8,
        padding: 16,
        backgroundColor: "#fff",
        borderTopWidth: 1,
        borderTopColor: "#eee",
    },
    cancelButton: {
        flex: 1,
        borderWidth: 1,
        borderColor: "#ddd",
        borderRadius: 4,
        paddingVertical: 12,
        alignItems: "center",
        justifyContent: "center",
    },
    cancelButtonText: {
        fontSize: 14,
        fontWeight: "600",
        color: "#333",
    },
    submitButton: {
        flex: 1,
        backgroundColor: "#EF7810",
        borderRadius: 4,
        paddingVertical: 12,
        alignItems: "center",
        justifyContent: "center",
    },
    submitButtonText: {
        fontSize: 16,
        fontWeight: "600",
        color: "#fff",
    },
});